create database brh;


create taBLE ATRIBUICAO(
    colaborador varchar2(10) not null,
	projeto integer not null,
	papel integer not null,
	constraint pk_atribuicao primary key (colaborador, projeto, papel)
);



create table DEPARTAMENTO (
	sigla varchar2(6) not null,
	nome varchar2(255) not null,
	chefe varchar2(10) not null,
	departamento_superior varchar2(6),
	constraint pk_departamento primary key (sigla),
	constraint fk_departamento_superior
		foreign key (departamento_superior)
		references brh.departamento (sigla)
);

create table ENDERECO_colaborador (
	id_endereco int not null,
    rua varchar(100) not null,
    cep varchar2(10) not null,
	estado char(2) not null,
	cidade varchar2(255) not null,
	bairro varchar2(255) not null,
    complemento varchar(255),
    id_colaborador int not null,
	constraint id_endereco primary key (cep)
    constraint fk_id_colaborador 
		foreign key (id_colaborador)
		references colaborador (matricula)
);

create table COLABORADOR (
	matricula varchar2(10) not null,
	cpf char(14) not null,
	nome varchar2(255) not null,
	salario decimal(10,2) not null,
	departamento varchar2(6) NOT NULL,
	cep varchar2(10) not null,
	logradouro varchar2(255) not null,
	complemento_endereco varchar(255),
	constraint pk_colaborador primary key (matricula),
	constraint fk_endereco_colaborador 
		foreign key (cep)
		references brh.endereco (cep)
);

create table TELEFONE_COLABORADOR(
	numero varchar2(20) not null,
	colaborador varchar2(10) not null,
	tipo char(1) default 'R' NOT null,
	constraint pk_telefone primary key (colaborador, numero),
	constraint fk_telefone_colaborador
		foreign key (colaborador)
		references brh.colaborador (matricula)
	
);

create table EMAIL_COLABORADOR(
	email varchar2(255) not null,
	colaborador varchar2(10) not null,
	tipo char(1) default 'R' NOT null,
	constraint pk_email primary key (colaborador, email),
	constraint fk_email_colaborador
		foreign key (colaborador)
		references brh.colaborador (matricula),
	
);

create table DEPENDENTES(
	cpf char(14) not null,
	nome varchar2(255) not null,
	data_nascimento date not null,
	parentesco varchar2(20) not null,
	colaborador varchar2(10) not null,
	constraint pk_dependente primary key (cpf),
	constraint fk_dependente_colaborador
		foreign key (colaborador)
		references brh.colaborador (matricula),
	
);

create table PROJETOS (
	id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 5) NOT NULL,
	nome varchar2(255) not null,
	responsavel varchar2(10),
	inicio date not null,
	fim date,
	constraint pk_projeto primary key (id),
	constraint fk_colaborador_projeto
		foreign key (responsavel)
		references brh.colaborador (matricula),
	constraint projeto_unico unique (nome)
);

create table ATRIBUICAO (
	colaborador varchar2(10) not null,
	projeto integer not null,
	papel integer not null,
	constraint pk_atribuicao primary key (colaborador, projeto, papel)
);